import { selfData } from "@/constant";
import { address } from "motion/react-client";

export function generatePersonStructuredData() {
  return {
    "@context": "https://schema.org",
    "@type": "Person",
    name: selfData.name,
    givenName: selfData.first_name,
    familyName: selfData.last_name,
    jobTitle: selfData.jobTitle,
    worksFor: {
      "@type": "Organization",
      name: selfData.workFor,
    },
    email: selfData.email,
    address: {
      "@type": "PostalAddress",
      addressLocality: selfData.current_location.city,
      addressRegion: selfData.current_location.state,
      addressCountry: selfData.current_location.country,
    },
    sameAs: [
      `https://github.com/${selfData.socials_username.github}`,
      `https://linkedin.com/in/${selfData.socials_username.linkedin}`,
      `https://twitter.com/${selfData.socials_username.twitter}`,
      `https://instagram.com/${selfData.socials_username.instagram}`,
    ],
    url: "https://devendra.vercel.app",
    description: selfData.bio,
  };
}

export function generateWebsiteStructuredData() {
  return {
    "@context": "https://schema.org",
    "@type": "WebSite",
    name: "Devendra Dhaked - Portfolio",
    url: "https://devendra.vercel.app",
    description:
      "Devendra Dhaked's portfolio featuring projects in React, Next.js, and modern web development",
    author: {
      "@type": "Person",
      name: selfData.name,
    },
    publisher: {
      "@type": "Person",
      name: selfData.name,
    },
    inLanguage: "en-US",
    copyrightYear: new Date().getFullYear(),
    copyrightHolder: {
      "@type": "Person",
      name: selfData.name,
    },
  };
}

export function generateOrganizationStructuredData() {
  return {
    "@context": "https://schema.org",
    "@type": "Organization",
    name: selfData.name,
    url: "https://devendra.vercel.app",
    logo: "https://devendra.vercel.app/images/logo.png",
    description: selfData.bio,
    founder: {
      "@type": "Person",
      name: selfData.name,
    },
    sameAs: [
      `https://github.com/${selfData.socials_username.github}`,
      `https://linkedin.com/in/${selfData.socials_username.linkedin}`,
      `https://twitter.com/${selfData.socials_username.twitter}`,
      `https://instagram.com/${selfData.socials_username.instagram}`,
    ],
  };
}

export function generateResumeStructuredData() {
  return {
    "@context": "https://schema.org",
    "@type": "DigitalDocument",
    name: "Devendra Dhaked Resume",
    description:
      "Professional resume of Devendra Dhaked - Software Developer specializing in Full-Stack Web Development",
    url: "https://devendra.vercel.app/resume",
    author: {
      "@type": "Person",
      name: selfData.name,
      email: selfData.email,
      jobTitle: selfData.jobTitle,
      worksFor: {
        "@type": "Organization",
        name: selfData.workFor,
      },
      address: {
        "@type": "PostalAddress",
        addressLocality: selfData.current_location.city,
        addressRegion: selfData.current_location.state,
        addressCountry: selfData.current_location.country,
      },
      sameAs: [
        `https://github.com/${selfData.socials_username.github}`,
        `https://linkedin.com/in/${selfData.socials_username.linkedin}`,
      ],
    },
    dateModified: new Date().toISOString(),
    fileFormat: "application/pdf",
    contentUrl: "https://devendra.vercel.app/docs/MyResume.pdf",
    downloadUrl: "https://devendra.vercel.app/docs/MyResume.pdf",
    keywords: [
      "Software Developer",
      "Full Stack Developer",
      "React Developer",
      "Software Engineer",
      "Java Developer",
      "Backend Developer",
      "Web Developer",
      "Frontend Developer",
      "Next.js Developer",
      "Spring Boot Developer",
      "JavaScript Developer",
      "Spring Framework",
      "Spring Boot",
      "Spring MVC",
      "Spring Security",
      "Spring Data JPA",
      "Spring Boot Microservices",
      "Spring Boot REST API",
      "Spring Boot Security",
      "Spring Boot Testing",
      "Java Core",
      "Java Collections",
      "Java Multithreading",
      "Java JDBC",
      "Java Hibernate",
      "Java JPA",
      "Java Design Patterns",
      "Java Unit Testing",
      "Java Performance Optimization",
      "React.js",
      "Next.js",
      "Java",
      "TypeScript",
      "HTML",
      "CSS",
      "JavaScript",
      "Node.js",
      "Express.js",
      "REST API",
      "GraphQL",
      "Microservices",
      "PostgreSQL",
      "MySQL",
      "MongoDB",
      "Docker",
      "Kubernetes",
      "Git",
      "Agile Development",
      "CI/CD",
      "DevOps Practices",
      "Cloud Computing (AWS, Azure, GCP)",
      "Software Testing",
      "Unit Testing",
      "Integration Testing",
      "System Design",
      "Data Structures and Algorithms",
      "Problem Solving",
      "Version Control with Git",
      "Responsive Web Design",
      "Cross-browser Compatibility",
      "Performance Optimization",
      "User Experience (UX) Design",
      "Accessibility Standards",
      "SEO Best Practices",
      "Agile Project Management",
      "RESTFUL API",
      "Hibernate",
      "JPA",
      "PostgreSQL",
      "MySQL",
      "MongoDB",
      "Docker",
      "Git",
      "Agile",
      "CI/CD",
      "DevOps",
      "Cloud Computing",
      "Problem Solver",
      "Team Player",
      "Self-motivated",
      "Continuous Learner",
      "Open Source Contributor",
      "Software Development",
      "Web Applications",
      "System Design",
      "Data Structures and Algorithms",
      "Agile Methodologies",
      "Microservices Architecture",
      "API Development",
      "Software Testing",
      "Version Control with Git",
      "Responsive Web Design",
      "Cross-browser Compatibility",
      "Performance Optimization",
      "User Experience (UX) Design",
      "Accessibility Standards",
      "SEO Best Practices",
      "Agile Project Management",
      "Scrum Methodology",
      "Kanban",
      "Software Documentation",
    ],
    educationalBackground: [
      {
        "@type": "EducationalOrganization",
        name: selfData.workFor,
        address: {
          "@type": "PostalAddress",
          addressLocality: selfData.current_location.city,
          addressRegion: selfData.current_location.state,
          addressCountry: selfData.current_location.country,
        },
        alumniOf: {
          "@type": "EducationalOrganization",
          name: selfData.workFor,
        },
        degree: "Bachelor of Technology in Information Technology",
        startDate: "2020-08-01", // Example start date
        endDate: "2024-05-31", // Example end date
        description: "Bachelor's degree in Information Technology from Poornima College of Engineering",
        city: "Jaipur",
        state: "Rajasthan",
        country: "India",  
      },
    ],
  };
}
