export const keywords = [
  "Devendra Dhaked",
  "Devendra",
  "Dhaked",
  "dhakeddevendra5", // GitHub username
  "devendra.vercel.app", // Portfolio URL
  "dhakeddevendra5@gmail.com", // Email for search
  "linkedin/in/dhakeddevendra5", // LinkedIn profile
  "Devendra Dhaked portfolio",
  "Devendra Dhaked developer",
  "Devendra Dhaked software engineer",
  "Devendra Dhaked Software developer",
  "Devendra Dhaked web developer",
  "Devendra Dhaked AI developer",
  "Devendra Dhaked full-stack developer",
  "Devendra Dhaked projects",
  "Devendra Dhaked resume",
  "Devendra Dhaked contact",

  "student developer portfolio",
  "web developer Bhubaneswar",
  "frontend developer India",
  "full-stack engineer portfolio",
  "open source web developer",
  "Next.js frontend portfolio",
  "React developer personal site",
  "software engineer portfolio",
  "AI developer portfolio",
  "Machine Learning Engineer",
  "Content Development Tech",
  "Unstop developer",
  "coding question developer",
  "technical question curator",
  "data bug resolution",
  "cloud developer",
  "DevOps enthusiast",
  "entry-level software engineer",
  "junior web developer",

  "C programming",
  "C++ programming",
  "Java developer",
  "JavaScript developer",
  "TypeScript developer",
  "Python developer",
  "HTML/CSS development",

  "React.js developer",
  "Next.js developer",
  "Framer Motion animations",
  "Tailwind CSS design",
  "Bootstrap framework",
  "ShadCN UI components",
  "responsive web design",
  "UI/UX development",
  "modern UI development",
  "Next.js Server Components",
  "Next.js Client Components",
  "CSS Modules",
  "SCSS",
  "Redux state management",

  "Express.js backend",
  "API Design",
  "MongoDB database",
  "Oracle SQL",
  "MySQL database",
  "PostgreSQL database",
  "Prisma ORM",
  "drizzle ORM",
  "serverless functions",
  "Next.js API routes",
  "Convex backend database",
  "REST API development",
  "GraphQL API",
  "WebSockets",

  "BERT model",
  "Machine Learning",
  "Deep Learning",
  "Generative AI",
  "Large Language Models (LLMs)",
  "LLaMA language model",
  "LangChain developer",
  "Gemini API integration",
  "Hugging Face API for AI",
  "Ollama local LLM",
  "Natural Language Processing (NLP)",
  "Computer Vision",
  "Prompt Engineering",
  "AI model fine-tuning",
  "TensorFlow",
  "PyTorch",
  "Keras",

  "Git version control",
  "GitHub collaboration",
  "Postman API testing",
  "Jest testing setup",
  "unit testing in Next.js",
  "API integration with Next.js",
  "Clerk authentication Next.js",
  "Firebase hosting",
  "Netlify deployment",
  "Vercel deployment",
  "Glitch development",
  "Replit development",
  "Docker developer",
  "Kubernetes basics",
  "CI/CD with GitHub Actions",
  "VS Code extensions",
  "Webpack",
  "Vite",
  "Figma UI/UX design",

  "Orphia AI Music Generator",
  "AI-powered music generation platform",
  "Meta MusicGen integration",
  "Custom LSTM model music",
  "Next.js music UI",
  "music personalization AI",
  "audio synthesis AI",
  "CppTest GenAI",
  "AI-powered C++ test generator",
  "LLaMA language model C++",
  "intelligent unit test scenarios",
  "automated test case generation",
  "test accuracy improvement",
  "CI/CD pipeline integration",
  "personal portfolio website Next.js",
  "EmailJs integration",
  "Framer Motion portfolio",
  "SEO optimization portfolio",
  "structured metadata website",
  "Open Graph tags SEO",
  "Google PageSpeed Insights optimization",
  "performance optimization web",
  "accessibility best practices",
  "AI mood journal app",
  "Instagram reel downloader app",
  "reel download tool",
  "Next.js story app",
  "24Verse stories app",
  "text to music AI generator",
  "resume parser AI",
  "developer resume scanner",
  "bug tracker app Next.js",
  "build your own API project",
  "real-time chat application",
  "e-commerce platform development",
  "portfolio website builder",
  "custom AI chatbot",
  "image generation AI project",
  "sentiment analysis tool",
  "full-stack project examples",
  "web application development",

  "HackerRank Problem Solving Certificate",
  "HackerRank Java Certificate",
  "HackerRank SQL Certificate",
  "HackerRank Python Certificate",
  "HackerRank JavaScript Certificate",
  "HackerRank Front-End Certificate",
  "Jspider Java Full Stack Developer Certificate",
  "Internsala C/C++ Certificate",
  "Samyak Python Certificate",

  "react portfolio example 2025",
  "Next.js app directory project",
  "modern web development portfolio",
  "best open source portfolio projects",
  "developer website examples",
  "personal web developer site",
  "tech blog and portfolio",
  "build portfolio with Tailwind CSS",
  "interactive resume website",
  "coding portfolio examples",
  "developer with AI projects",
  "best portfolio with AI features",
  "free tools for developers",
  "developer website inspiration",
  "SEO optimized portfolio site",
  "how to build a developer portfolio",
  "showcase coding projects",
  "web development trends 2025",
  "Information Techology student projects",
  "B.Tech Information Techology portfolio",
  "PCE student developer",
  "hire Next.js developer",
  "hire React developer",
  "freelance web developer",
  "internship software development",
  "student developer looking for job",

  "JavaScript",
  "HTML",
  "CSS",
  "Next.js",
  "React",
  "Tailwind",
  "Framer Motion",
  "PostgreSQL",
  "MongoDB",
  "Oracle SQL",
  "MySQL",
  "Vercel",
  "Clerk",
  "Ollama",
  "GitHub Actions",
  "API routes",
  "app router",
  "responsive UI",
  "dark mode toggle",
  "UI/UX",
  "full-stack",
  "AI",
  "Machine Learning",
  "Deep Learning",
  "Cloud Computing",
  "Firebase",
  "GraphQL",
  "REST API",
  "WebSockets",
  "Git",
  "GitHub",
  "VS Code",
  "Node.js",
  "Express.js",
  "Python",
  "C",
  "C++",
  "Java",
  "Spring Boot",
  "JUnit",
  "Docker",
  "Kubernetes",
  "Agile",
  "Scrum",
  "CI/CD",
  "DevOps",
  "Software Testing",
  "Unit Testing",
  "Integration Testing",
  "System Design",
  "Data Structures and Algorithms",
  "DSA",
  "Object-Oriented Programming",
  "OOP",
  "Functional Programming",
  "System Design",
  "Agile development",
  "Clean Code",
  "Scalable architecture",
];
